#!/usr/bin/env python
import sys
import time

build_date = sys.argv[1]
#build_date = '2010.05.18_0400.00-1'
build_date = build_date[:-3]
time_format = '''%Y.%m.%d_%H%M.%S'''
print time.mktime(time.strptime(build_date, time_format))
      
