#!/usr/bin/env python
import sys
import yaml
from yaml import CDumper as Dumper
import json
import pprint

with open(sys.argv[1], 'r') as f:
    data = f.read()

json = json.load(data)

pprint.pprint(yaml.dump(data, default_flow_style=False, Dumper=Dumper))


