#!/usr/bin/env python
import sys
from datetime import datetime
from time import mktime


buildTimestamp = sys.argv[1]
d = datetime.fromtimestamp(float(buildTimestamp)) 
print d.strftime('%Y-%m-%d %H:%M:%S')
