#!/usr/bin/env python
import sys
import yaml
import json


with open(sys.argv[1], 'r') as stream:
    data = yaml.load(stream)


print json.dumps(data, sort_keys=True, indent=4, separators=(',', ': '))
